site_name: training.nextflow.io
site_url: https://training.nextflow.io/
repo_url: https://github.com/nextflow-io/training
repo_name: nextflow-io/training

nav:
    - Home: index.md
    - Basic Training:
          - basic_training/index.md
          - Setup:
                - basic_training/setup/index.md
                - basic_training/setup/local.md
                - basic_training/setup/gitpod.md
                - basic_training/setup/version.md
          - basic_training/intro.md
          - Simple RNA-Seq pipeline:
                - basic_training/rnaseq_pipeline/index.md
                - basic_training/rnaseq_pipeline/params.md
                - basic_training/rnaseq_pipeline/create_index.md
                - basic_training/rnaseq_pipeline/collect_reads.md
                - basic_training/rnaseq_pipeline/quantification.md
                - basic_training/rnaseq_pipeline/quality_control.md
                - basic_training/rnaseq_pipeline/completion.md
                - basic_training/rnaseq_pipeline/custom_scripts.md
                - basic_training/rnaseq_pipeline/github.md
          - Dependencies and containers:
                - basic_training/containers/index.md
                - basic_training/containers/docker.md
                - basic_training/containers/singularity.md
                - basic_training/containers/conda.md
                - basic_training/containers/biocontainers.md
          - Channels:
                - basic_training/channels/index.md
                - basic_training/channels/types.md
                - basic_training/channels/factories.md
                - basic_training/channels/file_formats.md
          - basic_training/processes.md
          - basic_training/operators.md
          - basic_training/groovy.md
          - basic_training/modules.md
          - basic_training/config.md
          - basic_training/executors.md
          - basic_training/tower.md
          - basic_training/cache_and_resume.md
          - basic_training/debugging.md
    - Hands on:
          - hands_on/index.md
          - hands_on/01_datasets.md
          - hands_on/02_workflow.md
          - hands_on/03_setup.md
          - hands_on/04_implementation.md
    - help.md

theme:
    name: material
    custom_dir: docs/assets/overrides
    language: en
    logo: assets/img/nextflow_logo_mono.svg
    favicon: assets/img/nf-square.png
    palette:
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/weather-night
              name: Switch to light mode
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
    font:
        text: Inter
    features:
        - content.action.edit
        - content.code.annotate
        - content.code.copy
        - navigation.footer
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - navigation.tracking
        - search.share
        - toc.follow
    icon:
        repo: fontawesome/brands/github
extra_css:
    - assets/stylesheets/extra.css

# Set in docs/assets/overrides/partials/copyright.html
# so that we can have links and stuff
# copyright: Seqera

extra:
    analytics:
        provider: google
        property: G-244N3GEN75
    consent:
        title: Cookie consent
        description: >-
            We use cookies to recognize your repeated visits and preferences, as well
            as to measure the effectiveness of our documentation and whether users
            find what they're searching for. With your consent, you're helping us to
            make our documentation better.
    # Overriden in docs/assets/overrides/partials/social.html
    # Still needs to be set to something here so that the partial is used
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/nextflowio
          name: Nextflow on twitter
markdown_extensions:
    - admonition
    - attr_list
    - md_in_html
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.snippets:
          base_path: ["."]
    - pymdownx.superfences
    - tables
    - toc:
          title: On this page
          permalink: true
plugins:
    - search
    - social:
          cards: !ENV [CARDS, true]
          cards_color:
              fill: "#27AE60"
              text: "#FFFFFF"
